1. Импортируйте пакет numpy под именем np

In [2]:
import numpy as np

2. Распечатайте версию numpy

In [4]:
print(np.__version__)

1.26.4


3. Создайте вектор со значениями от 10 до 49 

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [6]:
a = np.arange(10,50,1)

In [8]:
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


4. Перевернуть вектор (первый элемент становится последним)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [12]:
b = np.arange(49,9,-1)
print(b)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


5. Создайте массив 5x5 со случайными значениями и найдите среднее значение и медиану для каждой строки

In [14]:
A = np.random.random((5,5))
print(A)

[[0.51609562 0.76866124 0.48192639 0.89177974 0.60803128]
 [0.09057807 0.76897086 0.61007048 0.32783055 0.70735952]
 [0.71727115 0.61204576 0.7105181  0.71870435 0.19838955]
 [0.55674705 0.67065393 0.68158698 0.22791579 0.92426835]
 [0.40000958 0.65781408 0.21381417 0.68342734 0.9608959 ]]


array([0.78682331, 0.56270935, 0.53744539, 0.70048075, 0.50336328])

In [16]:
np.mean(A,axis=1)

array([0.65329885, 0.5009619 , 0.59138578, 0.61223442, 0.58319221])

array([0.77621004, 0.63715337, 0.49428744, 0.81732248, 0.43085952])

6. Преобразуйте одномерный массив из 27 элементов целого типа в трехмерный (3x3x3)

In [18]:
a = np.array([x for x in range(27)])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [20]:
a.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

7. Преобразуйте все элементы массива numpy из типа данных float в integer

In [22]:
a = np.array([[3.5, 1.9, 8.45], [4.7, 7.9, 1.9]])

[[3 1 8]
 [4 7 1]]


8. Преобразуйте двоичный массив numpy [[1, 0, 0], [1, 1, 1],  [0, 0, 1]] (содержащий только 0 и 1) в логический массив numpy

In [26]:
a = np.array([[1, 0, 0], [1, 1, 1],  [0, 0, 1]])

[[ True False False]
 [ True  True  True]
 [False False  True]]


In [28]:
c = np.array(a, dtype=bool)

In [30]:
print(c)

[[ True False False]
 [ True  True  True]
 [False False  True]]


9. Расположите 2 массива numpy горизонтально (hstack), т.е. 2 массива, имеющих одинаковое 1-е измерение (количество строк в 2D-массивах)

In [34]:
a1 = np.array([[1,2,3], [4,5,6]])
a2 = np.array([[7,8,9], [10,11,12]])

In [36]:
h = np.hstack((a1, a2))
h

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


10. Расположите 2 массива numpy вертикально (vstack), т.е. 2 массива, имеющие одинаковое последнее измерение (количество столбцов в 2D-массивах)

In [199]:
a1 = np.array([[1,2],
 [3,4],
 [5,6]])

a2 = np.array([[7,8],
 [9,10],
 [10,11]])

In [211]:
print(a1.reshape(3,2))
print(a2.reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]
[[ 7  8]
 [ 9 10]
 [10 11]]


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [10 11]]


11. Из 2 массивов numpy извлеките индексы, в которых совпадают элементы (np.where)

In [149]:
a = np.array([1,2,3,4,5])
b = np.array([1,3,2,4,5])


(array([0, 3, 4], dtype=int64),)


In [165]:
np.where(a==b)

(array([0, 3, 4], dtype=int64),)

12. Выведите результат умножения 2 матриц (в виде массива numpy)

In [40]:
a = np.array([[1,2,3], 
 [4,5,6], 
 [7,8,9]])

b = np.array([[2,3,4], 
 [5,6,7], 
 [8,9,10]])

[[ 36  42  48]
 [ 81  96 111]
 [126 150 174]]


In [44]:
n = a @ b
print(n)

[[ 36  42  48]
 [ 81  96 111]
 [126 150 174]]


13. Выведите транспонированную матрицу

In [107]:
a = np.array([[1,2,3], 
 [4,5,6], 
 [7,8,9]])

[[1 4 7]
 [2 5 8]
 [3 6 9]]


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [109]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

14. Вычислите синус массива углов (в радианах) с помощью NumPy

In [46]:
angles = np.array([3.14, 3.14/2, 6.28])

In [48]:
print(np.sin(angles))

[ 0.00159265  0.99999968 -0.0031853 ]


[ 0.00159265  0.99999968 -0.0031853 ]


15. Отсортировать вектор

In [50]:
v = np.random.random(size=[10])
print(v)

[0.28401802 0.41521493 0.03355877 0.85738966 0.26415378 0.39873178
 0.15036387 0.84097703 0.99262194 0.29981043]


[0.13178341 0.14962622 0.26204075 0.30821184 0.34446024 0.45199466
 0.51581108 0.79408365 0.87313982 0.88810901]


In [54]:
v.sort()
print(v)

[0.03355877 0.15036387 0.26415378 0.28401802 0.29981043 0.39873178
 0.41521493 0.84097703 0.85738966 0.99262194]


16. Проверить, одинаковы ли два NumPy массива

In [56]:
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5])

In [62]:
c = a == b
print(c)

[ True  True  True  True  True]


In [64]:
np.array_equal(a, b)

True

17. В одномерном массиве заменить максимальный элемент на ноль

In [68]:
Z = np.random.random(10)

In [70]:
print(Z)

[0.82746195 0.11094377 0.42184101 0.85833313 0.24840972 0.94520577
 0.75256231 0.36730996 0.54505941 0.99639014]


array([0.16782157, 0.13655578, 0.59454878, 0.02957322, 0.81242629,
       0.71645444, 0.48757387, 0.05812814, 0.21499663, 0.24011352])

[0.16782157 0.13655578 0.59454878 0.02957322 0.         0.71645444
 0.48757387 0.05812814 0.21499663 0.24011352]


In [72]:
Z[Z==max(Z)] = 0
print(Z)

[0.82746195 0.11094377 0.42184101 0.85833313 0.24840972 0.94520577
 0.75256231 0.36730996 0.54505941 0.        ]


18. Замените все нечетные числа одномерного массива на -1.

In [74]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
arr[1::2] = -1

In [80]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [78]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. Замените все элементы в массиве NumPy больше 30 или меньше 5 новым значением 10 

In [7]:
arr = np.array([0, 1, 20, 3, 4, 5, 6, -7, 8, 90])

In [23]:
arr[arr>30] = 10
arr[arr<5] = 10

In [25]:
print(arr)

[10 10 20 10 10  5  6 10  8 10]


20. Отсортируйте двумерный массив по столбцам

In [ ]:
a = np.array([[11,5,3], 
 [4,15,6], 
 [7,8,19]])

array([[ 4,  5,  3],
       [ 7,  8,  6],
       [11, 15, 19]])

In [271]:
a.sort()
print(a)

[[ 3  5 11]
 [ 4  6 15]
 [ 7  8 19]]
